run:
	# time ipython3 calculdes.py | tee calculdes.log
	time runipy -o Calcul_d_une_paire_de_des_un_peu_particuliers.ipynb 2>&1 | tee Calcul_d_une_paire_de_des_un_peu_particuliers.log
	# --html Calcul_d_une_paire_de_des_un_peu_particuliers..html


testmyfork:
	time ~/runipy/runipy.bin --logback -o Calcul_d_une_paire_de_des_un_peu_particuliers.ipynb 2>&1 | tee Calcul_d_une_paire_de_des_un_peu_particuliers.log
